export const S3_FOLDER_NAMES = {
    EVENT: "EVENT",
    FAQ: "FAQ",
    NOTICE: "NOTICE",
    INQUIRY: "INQUIRY",
    INQUIRY_ANSWER: "INQUIRY_ANSWER",
    ADMISSION_TICKET_IMAGE: "ADMISSION_TICKET_IMAGE",
    ADMISSION_TICKET_PDF: "ADMISSION_TICKET_PDF",
} as const;
