name: Partnership CI

on:
    pull_request:
        branches:
            - main
            - develop
        paths:
            - "partnership-app/**"
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "yarn"

            - name: Install Dependencies
              run: yarn install --frozen-lockfile
              working-directory: ./partnership-app

            - name: Type Check & Lint
              run: yarn lint
              working-directory: ./partnership-app

            - name: Build
              run: yarn build
              working-directory: ./partnership-app

            - name: Archive Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-files
                  path: partnership-app/dist/
                  retention-days: 7
