name: Partnership CD

on:
    pull_request:
        branches:
            - main
            - develop
        types:
            - closed
        paths:
            - "partnership-app/**"
    workflow_dispatch:

env:
    AWS_REGION: ${{ secrets.AWS_REGION }}
    NODE_VERSION: "22"

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "yarn"

            - name: Install Dependencies
              run: yarn install --frozen-lockfile
              working-directory: ./partnership-app

            - name: Type Check & Lint
              run: |
                  yarn lint
              working-directory: ./partnership-app

            - name: Build Application
              run: yarn build
              working-directory: ./partnership-app
              env:
                  CI: false

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Deploy to S3
              run: |
                  aws s3 sync ./dist s3://mosu-partnership --delete --cache-control "public,max-age=31536000" --exclude "*.html"
                  aws s3 sync ./dist s3://mosu-partnership --cache-control "public,max-age=0,must-revalidate" --include "*.html"
                  echo " Deployed to: https://mosu-partnership.s3.amazonaws.com/"
              working-directory: ./partnership-app

            - name: Deployment Complete
              run: |
                  echo "✅ Deployment successful!"
